# Generated by Django 4.2.5 on 2023-11-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='animalsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animals_image', models.ImageField(null=True, upload_to='images')),
                ('animals_heading', models.CharField(max_length=1000)),
                ('animals_content', models.CharField(max_length=2000)),
                ('animals_price', models.IntegerField(max_length=6)),
                ('animals_isStock', models.BooleanField(default=False)),
            ],
        ),
    ]
